djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('hihotel/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('reservation/<int:pk>/', views.reservation2, name='reservation.html'),
    path('reservation/', views.reservation1, name='reservation.html'),
    path('reservation/add', views.reservationadd, name='reservationadd'),
    path('admin/home', views.home, name='home'),
    path('admin/', views.login, name='login'),
    path("admin/logout/", views.logout_request, name="logout"),
    path("admin/profile/", views.profile, name="profile"),
    path("admin/change_password/", views.change_password, name='change_password'),
    path('admin/floor/', views.floor, name='floor'),
    path('admin/floor/add', views.addfloor, name='addfloor'),
    path('admin/floor/afloor', views.afloor, name='afloor'),
    #     path('admin/floor/update/<int:pk>', views.update_floor, name='update_floor'),
    path('admin/update_floor/<str:pk>/', views.updateFloor, name='update_floor'),
    path('admin/floor/del/<int:pk>', views.delete_floor, name='delete_floor'),
    path('admin/room/', views.room, name='room'),
    path('admin/room/add', views.addroom, name='addroom'),
    path('admin/room/aroom', views.aroom, name='aroom'),
    #     path('admin/room/upfloor/<int:pk>', views.uproom, name='uproom'),
    path('admin/update_room/<str:pk>/', views.updateRoom, name='update_room'),
    path('admin/room/del/<int:pk>', views.delete_room, name='delete_room'),
    path('admin/roomkind/', views.roomkind, name='roomkind'),
    path('admin/addroomkind', views.addroomkind, name='addroomkind'),
    path('admin/update_roomkind/<str:pk>/', views.updateRoomkind, name='update_roomkind'),
    path('admin/delete_roomkind/<str:pk>/', views.deleteRoomKind, name='delete_roomkind'),
    path('admin/bookroom/', views.bookroom, name='bookroom'),
    path('admin/bookroom/edit/<int:idRequest>/<str:status>/', views.editRequest, name='editRequest'),
    path('admin/bookroom/delete/<str:idRequest>/', views.deleteRequest, name="deleteRequest"),
    path('admin/bookroom/filter/<str:idRequest>/', views.filterRoom, name="filterRoom"),
    path('admin/bookroom/bookfilter/', views.booking, name="booking"),
    path('admin/booking/', views.bookingManage, name="bookingManage"),
    path('admin/booking/edit/<int:id>/<str:status>/', views.bookingEdit, name="bookingEdit"),
    path('admin/booking/delete/<int:id>/', views.bookingDelete, name="bookingDelete"),
]

polls/models.py
from django.db import models


class Floor(models.Model):
    idFloor = models.BigAutoField(primary_key=True)
    nameFloor = models.CharField(max_length=100)

    class Meta:
        db_table = 'Floor'


class RoomKind(models.Model):
    KIND = [
        ('STD-S', 'Standard - Singer bed'),
        ('STD-D', 'Standard - Double bed'),
        ('SUP-S', 'Superior - Single bed'),
        ('SUP-D', 'Superior - Double bed'),
    ]
    idKind = models.BigAutoField(primary_key=True)
    nameKind = models.CharField(max_length=100, choices=KIND)
    price = models.CharField(max_length=100)
    descript = models.TextField()

    class Meta:
        db_table = 'RoomKind'


class RoomPicture(models.Model):
    idPicture = models.BigAutoField(primary_key=True)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    linkPicture = models.CharField(max_length=100)

    class Meta:
        db_table = 'RoomPicture'


class Room(models.Model):
    STATUS = [
        ('OK', 'Phòng sẵn sàng'),
        ('ER', 'Phòng hỏng')
    ]
    idRoom = models.BigAutoField(primary_key=True)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    nameRoom = models.CharField(max_length=100)
    status = models.CharField(max_length=100, choices=STATUS, default='OK')

    class Meta:
        db_table = 'Room'


class CustomerInfor(models.Model):
    GENDER = [
        ('Na', 'Nam'),
        ('Nu', 'Nữ'),
        ('Kh', 'Khác')
    ]
    idCustomer = models.BigAutoField(primary_key=True)
    nameCustomer = models.CharField(max_length=50)
    gender = models.CharField(max_length=100, choices=GENDER)
    identityCard = models.CharField(max_length=12)
    phoneNumber = models.CharField(max_length=12)
    email = models.CharField(max_length=30)

    class Meta:
        db_table = 'CustomerInfo'


class CustomerRequest(models.Model):
    STATUS = [
        ('CD', 'Chờ duyệt'),
        ('HL', 'Hợp lệ'),
        ('KHL', 'Không hợp lệ')
    ]
    idRequest = models.BigAutoField(primary_key=True)
    customer = models.ForeignKey(CustomerInfor, on_delete=models.CASCADE)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    dateCheckin = models.DateTimeField()
    dateCheckout = models.DateTimeField()
    numberOfRoom = models.IntegerField()
    numberOfChildren = models.IntegerField()
    numberOfAdults = models.IntegerField()
    status = models.CharField(max_length=100, choices=STATUS, default='CD')
    note = models.TextField(default="")

    class Meta:
        db_table = 'CustomerRequest'

class Booking(models.Model):
    STATUS = [
        ('DN', 'Đã nhận phòng'),
        ('DH', 'Đã hủy'),
        ('CN', 'Chờ nhận phòng')
    ]
    idBooking = models.BigAutoField(primary_key=True)
    customerRequest = models.ForeignKey(CustomerRequest, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    status = models.CharField(max_length=100, choices=STATUS, default='CN')
    note = models.CharField(max_length=100)

    class Meta:
        db_table = 'Booking'

polls/forms.py
from django import forms
from .models import *


class RoomKindForm(forms.ModelForm):
    class Meta:
        model = RoomKind
        fields = ('idKind', 'nameKind', 'price', 'descript')


class FloorForm(forms.ModelForm):
    class Meta:
        model = Floor
        fields = ('idFloor', 'nameFloor')


class RoomForm(forms.ModelForm):
    # floor = forms.ModelChoiceField(queryset=Floor.objects.all(),
    #                                 empty_label="............")
    # kind = forms.ModelChoiceField(queryset=RoomKind.objects.all(),
    #                                 empty_label="............")
    class Meta:
        model = Room
        fields = ('idRoom', 'floor', 'kind', 'nameRoom', 'status')

polls/views.py
from email.policy import HTTP
from django.http import HttpResponse
from .models import *
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
# from HotelManage.polls.models import RoomKind
from .forms import *
from .models import *


### Trang chủ và form yêu cầu đặt phòng - Dương
def index(request):
    listRoomKind = RoomKind.objects.all()
    listPicture = RoomPicture.objects.all()

    return render(request, 'polls/index.html', {'listRoomKind': listRoomKind, 'listPicture': listPicture})


def reservation1(request):
    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html', {'listRoomKind': listRoomKind})


def reservation2(request, pk):
    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html', {'listRoomKind': listRoomKind, "idKind": pk})


def reservationadd(request):
    # Thêm thông tin khách hàng
    name = request.POST['name']
    gender = request.POST['gender']
    identitycard = request.POST['identitycard']
    email = request.POST['email']
    phone = request.POST['phone']
    cus = CustomerInfor(nameCustomer=name, gender=gender, identityCard=identitycard, phoneNumber=phone, email=email)
    cus.save()
    idCus = cus.idCustomer

    # Thêm vào bảng yêu cầu khách hàng
    kindroom = request.POST['kindroom']
    kind = RoomKind.objects.get(idKind=kindroom)
    customer = CustomerInfor.objects.get(idCustomer=idCus)
    checkInt = request.POST['cin']
    checkOut = request.POST['cout']
    numberRoom = int(request.POST['numberRoom'])
    numberChildren = int(request.POST['numberChildren'])
    numberAdults = int(request.POST['numberAdults'])
    note = request.POST['note']
    rq = CustomerRequest(kind=kind, customer=customer, dateCheckin=checkInt, dateCheckout=checkOut,
                         numberOfRoom=numberRoom, numberOfChildren=numberChildren, numberOfAdults=numberAdults,
                         note=note)
    rq.save()

    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html',
                  {'success': 'Request sent to the hotel!', 'listRoomKind': listRoomKind})


###

### Trang chủ admin -
def home(request):
    return render(request, 'polls/admin/home.html')


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse("polls:home"))
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="polls/admin/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    return render(request, 'polls/admin/login.html', messages.error(request, "You have successfully logged out."))


def profile(request):
    return render(request, 'polls/admin/profile.html')


# đổi mật khẩu
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('polls:change_password')
        else:
            messages.error(request, 'Please re-enter your password.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'polls/admin/change_password.html', {
        'form': form
    })


###

### Quản lý phòng và tầng - Huyền
def floor(request):
    polls_floor_list = Floor.objects.filter().order_by('idFloor')
    context = {'Floor': polls_floor_list}
    return render(request, 'polls/admin/floor.html', context)


def addfloor(request):
    return render(request, 'polls/admin/floor_add.html')


def afloor(request):
    if request.method == 'POST':
        name_floor = request.POST['name']

        fl = Floor(nameFloor=name_floor)
        fl.save()

        return floor(request)
    else:
        return render(request, 'polls/admin/error.html')


def delete_floor(request, pk):
    item = Floor.objects.get(idFloor=pk)

    item.delete()
    return floor(request)


def updateFloor(request, pk):
    floor = Floor.objects.get(idFloor=pk)
    form = FloorForm(instance=floor)
    if request.method == 'POST':
        form = FloorForm(request.POST, instance=floor)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/floor/')

    context = {'form': form}
    return render(request, 'polls/admin/floor_update.html', context)


# quản lý phòng
def room(request):
    list_floor = Floor.objects.filter()
    polls_room = Room.objects.filter().order_by('idRoom')
    return render(request, 'polls/admin/room.html', {'Room': polls_room})


def delete_room(request, pk):
    item = Room.objects.get(idRoom=pk)

    item.delete()

    return room(request)


def addroom(request):
    list_floor = Floor.objects.filter()
    list_roomkind = RoomKind.objects.filter()
    return render(request, 'polls/admin/room_add.html', {'floor': list_floor, 'roomkind': list_roomkind})


def aroom(request):
    if request.method == 'POST':
        name_room = request.POST['name_room']
        id_floor = request.POST['tang']
        id_roomkind = request.POST['loaiphong']
        trangthai = request.POST['trangthai']

        itemfloor = Floor.objects.get(idFloor=id_floor)
        itemRoomkind = RoomKind.objects.get(idKind=id_roomkind)

        addroom = Room(floor=itemfloor, kind=itemRoomkind, nameRoom=name_room, status=trangthai)
        addroom.save()
        return room(request)
    else:
        return render(request, 'polls/admin/error.html')


def updateRoom(request, pk):
    room = Room.objects.get(idRoom=pk)
    form = RoomForm(instance=room)
    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/room/')

    context = {'form': form}
    return render(request, 'polls/admin/room_update.html', context)


###

### Quản lý loại phòng - Ngân
def roomkind(request):
    roomkinds = RoomKind.objects.all()
    return render(request, 'polls/admin/roomkind.html', {'roomkinds': roomkinds})


def addroomkind(request):
    form = RoomKindForm()
    if request.method == 'POST':
        form = RoomKindForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/roomkind/')

    context = {'form': form}
    return render(request, 'polls/admin/addroomkind.html', context)


def updateRoomkind(request, pk):
    roomkind = RoomKind.objects.get(idKind=pk)
    form = RoomKindForm(instance=roomkind)
    if request.method == 'POST':
        form = RoomKindForm(request.POST, instance=roomkind)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/roomkind/')

    context = {'form': form}
    return render(request, 'polls/admin/addroomkind.html', context)


def deleteRoomKind(request, pk):
    roomkind = RoomKind.objects.get(idKind=pk)
    roomkind.delete()

    return redirect('/hihotel/admin/roomkind/')


###

### Quản lý yêu cầu đặt phòng và lập đơn đặt phòng - Thư
def bookroom(request):
    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status
    }

    return render(request, 'polls/admin/bookroom.html', res)


def editRequest(request, idRequest, status):
    record = CustomerRequest.objects.get(idRequest=idRequest)
    record.status = status
    record.save(update_fields=['status'])

    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status,
        "message": "Update success!"
    }

    return render(request, 'polls/admin/bookroom.html', res)


def deleteRequest(request, idRequest):
    CustomerRequest.objects.filter(idRequest=idRequest).delete()

    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status,
        "message": "Delete success!"
    }

    return render(request, 'polls/admin/bookroom.html', res)


def filterRoom(request, idRequest):
    dateCheckin = CustomerRequest.objects.filter(idRequest=idRequest)[0].dateCheckin
    dateCheckout = CustomerRequest.objects.filter(idRequest=idRequest)[0].dateCheckout
    kind = CustomerRequest.objects.filter(idRequest=idRequest)[0].kind
    numberOfRoom = CustomerRequest.objects.filter(idRequest=idRequest)[0].numberOfRoom

    listRoomOfKind = Room.objects.filter(kind=kind, status='OK')
    listRoom = Booking.objects.select_related('customerRequest')
    listExcept = []
    listReturn = []

    for i in listRoom:
        if i.status != 'DH':
            if kind.idKind == i.customerRequest.kind.idKind:
                if i.customerRequest.status != 'KHL':

polls/templates/polls/admin/include/link_lib.html
{% load static %}

<!-- Bootstrap Styles-->
<link href="{% static 'polls/admin/assets/css/bootstrap.css' %}" rel="stylesheet" />
<!-- FontAwesome Styles-->
<link href="{% static 'polls/admin/assets/css/font-awesome.css' %}" rel="stylesheet" />
<link href="{% static 'polls/fonts/font-awesome/css/all.css' %}" rel="stylesheet" />
<!-- Morris Chart Styles-->
<link href="{% static 'polls/admin/assets/js/morris/morris-0.4.3.min.css' %}" rel="stylesheet" />
<!-- Custom Styles-->
<link href="{% static 'polls/admin/assets/css/custom-styles.css' %}" rel="stylesheet" />
<link href="{% static 'polls/admin/assets/css/style.css' %}" rel="stylesheet" />
<!-- Google Fonts-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

<!-- Data table -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css"></script>

<script>
    $(document).ready(function() {
        $('#table').dataTable({
            "ordering": false,
            "language": {
            "sProcessing":   "Processing...",
            "sLengthMenu":   "Line number in page: _MENU_",
            "sZeroRecords":  "No result",
            "sInfoPostFix":  "",
            "sSearch":       "Search:",
            "sUrl":          "",
            "oPaginate": {
                "sFirst":    "First",
                "sPrevious": "Prev",
                "sNext":     "Next",
                "sLast":     "Last"
                }
            }
        });
    });
</script>

polls/templates/polls/admin/include/nav_horizontal.html
<nav class="navbar navbar-default top-navbar" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">  </a>
    </div>

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                <i class="fa fa-user fa-fw"></i>Hi, {{request.user.username}} <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="{% url 'polls:profile' %}"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="{% url 'polls:change_password' %}"><i class="fa fa-user fa-fw"></i> Change Password</a>
                </li>
                <li class="divider"></li>
                <li><a href="{% url 'polls:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
</nav>

polls/templates/polls/admin/include/nav_vertical.html
<nav class="navbar-default navbar-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="main-menu">
            <li>
                <a id="home_page" href="{% url 'polls:home' %}"><i class="fas fa-home"></i></i> Home</a>
            </li>
            <li>
                <a id="floor_page" href="{% url 'polls:floor'%}"><i class="fas fa-building"></i> Floor</a>
            </li>
            <li>
                <a id="room_page" href="{% url 'polls:room' %}"><i class="fa fa-desktop"></i> Room</a>
            </li>
            <li>
                <a id="kind_page" href="{% url 'polls:roomkind' %}"><i class="fas fa-th-list"></i> Room kind</a>
            </li>
            <li>
                <a id="booking_page" href="{% url 'polls:bookroom' %}"><i class="fas fa-check-square"></i> Reservation request</a>
            </li>
            <li>
                <a id="booking_page" href="{% url 'polls:bookingManage' %}"><i class="fas fa-check-double"></i> Booking</a>
            </li>
            <li>
                <a href="{% url 'polls:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </li>
        </ul>
    </div>
</nav>

<!-- <script>
    $(document).ready(function() {
        if ($('#name_page').html() == "Home") {
            $('#home_page').class
        }
        class="active-menu"
    });
</script> -->