djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('hihotel/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('reservation/<int:pk>/', views.reservation2, name='reservation.html'),
    path('reservation/', views.reservation1, name='reservation.html'),
    path('reservation/add', views.reservationadd, name='reservationadd'),
    path('admin/home', views.home, name='home'),
    path('admin/', views.login, name='login'),
    path("admin/logout/", views.logout_request, name="logout"),
    path("admin/profile/", views.profile, name="profile"),
    path("admin/change_password/", views.change_password, name='change_password'),
    path('admin/floor/', views.floor, name='floor'),
    path('admin/floor/add', views.addfloor, name='addfloor'),
    path('admin/floor/afloor', views.afloor, name='afloor'),
    #     path('admin/floor/update/<int:pk>', views.update_floor, name='update_floor'),
    path('admin/update_floor/<str:pk>/', views.updateFloor, name='update_floor'),
    path('admin/floor/del/<int:pk>', views.delete_floor, name='delete_floor'),
    path('admin/room/', views.room, name='room'),
    path('admin/room/add', views.addroom, name='addroom'),
    path('admin/room/aroom', views.aroom, name='aroom'),
    #     path('admin/room/upfloor/<int:pk>', views.uproom, name='uproom'),
    path('admin/update_room/<str:pk>/', views.updateRoom, name='update_room'),
    path('admin/room/del/<int:pk>', views.delete_room, name='delete_room'),
    path('admin/roomkind/', views.roomkind, name='roomkind'),
    path('admin/addroomkind', views.addroomkind, name='addroomkind'),
    path('admin/update_roomkind/<str:pk>/', views.updateRoomkind, name='update_roomkind'),
    path('admin/delete_roomkind/<str:pk>/', views.deleteRoomKind, name='delete_roomkind'),
    path('admin/bookroom/', views.bookroom, name='bookroom'),
    path('admin/bookroom/edit/<int:idRequest>/<str:status>/', views.editRequest, name='editRequest'),
    path('admin/bookroom/delete/<str:idRequest>/', views.deleteRequest, name="deleteRequest"),
    path('admin/bookroom/filter/<str:idRequest>/', views.filterRoom, name="filterRoom"),
    path('admin/bookroom/bookfilter/', views.booking, name="booking"),
    path('admin/booking/', views.bookingManage, name="bookingManage"),
    path('admin/booking/edit/<int:id>/<str:status>/', views.bookingEdit, name="bookingEdit"),
    path('admin/booking/delete/<int:id>/', views.bookingDelete, name="bookingDelete"),
]

polls/models.py
from django.db import models


class Floor(models.Model):
    idFloor = models.BigAutoField(primary_key=True)
    nameFloor = models.CharField(max_length=100)

    class Meta:
        db_table = 'Floor'


class RoomKind(models.Model):
    KIND = [
        ('STD-S', 'Standard - Singer bed'),
        ('STD-D', 'Standard - Double bed'),
        ('SUP-S', 'Superior - Single bed'),
        ('SUP-D', 'Superior - Double bed'),
    ]
    idKind = models.BigAutoField(primary_key=True)
    nameKind = models.CharField(max_length=100, choices=KIND)
    price = models.CharField(max_length=100)
    descript = models.TextField()

    class Meta:
        db_table = 'RoomKind'


class RoomPicture(models.Model):
    idPicture = models.BigAutoField(primary_key=True)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    linkPicture = models.CharField(max_length=100)

    class Meta:
        db_table = 'RoomPicture'


class Room(models.Model):
    STATUS = [
        ('OK', 'Phòng sẵn sàng'),
        ('ER', 'Phòng hỏng')
    ]
    idRoom = models.BigAutoField(primary_key=True)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    nameRoom = models.CharField(max_length=100)
    status = models.CharField(max_length=100, choices=STATUS, default='OK')

    class Meta:
        db_table = 'Room'


class CustomerInfor(models.Model):
    GENDER = [
        ('Na', 'Nam'),
        ('Nu', 'Nữ'),
        ('Kh', 'Khác')
    ]
    idCustomer = models.BigAutoField(primary_key=True)
    nameCustomer = models.CharField(max_length=50)
    gender = models.CharField(max_length=100, choices=GENDER)
    identityCard = models.CharField(max_length=12)
    phoneNumber = models.CharField(max_length=12)
    email = models.CharField(max_length=30)

    class Meta:
        db_table = 'CustomerInfo'


class CustomerRequest(models.Model):
    STATUS = [
        ('CD', 'Chờ duyệt'),
        ('HL', 'Hợp lệ'),
        ('KHL', 'Không hợp lệ')
    ]
    idRequest = models.BigAutoField(primary_key=True)
    customer = models.ForeignKey(CustomerInfor, on_delete=models.CASCADE)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    dateCheckin = models.DateTimeField()
    dateCheckout = models.DateTimeField()
    numberOfRoom = models.IntegerField()
    numberOfChildren = models.IntegerField()
    numberOfAdults = models.IntegerField()
    status = models.CharField(max_length=100, choices=STATUS, default='CD')
    note = models.TextField(default="")

    class Meta:
        db_table = 'CustomerRequest'

class Booking(models.Model):
    STATUS = [
        ('DN', 'Đã nhận phòng'),
        ('DH', 'Đã hủy'),
        ('CN', 'Chờ nhận phòng')
    ]
    idBooking = models.BigAutoField(primary_key=True)
    customerRequest = models.ForeignKey(CustomerRequest, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    status = models.CharField(max_length=100, choices=STATUS, default='CN')
    note = models.CharField(max_length=100)

    class Meta:
        db_table = 'Booking'

polls/forms.py
from django import forms
from .models import *


class RoomKindForm(forms.ModelForm):
    class Meta:
        model = RoomKind
        fields = ('idKind', 'nameKind', 'price', 'descript')


class FloorForm(forms.ModelForm):
    class Meta:
        model = Floor
        fields = ('idFloor', 'nameFloor')


class RoomForm(forms.ModelForm):
    # floor = forms.ModelChoiceField(queryset=Floor.objects.all(),
    #                                 empty_label="............")
    # kind = forms.ModelChoiceField(queryset=RoomKind.objects.all(),
    #                                 empty_label="............")
    class Meta:
        model = Room
        fields = ('idRoom', 'floor', 'kind', 'nameRoom', 'status')

polls/views.py
from email.policy import HTTP
from django.http import HttpResponse
from .models import *
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
# from HotelManage.polls.models import RoomKind
from .forms import *
from .models import *


### Trang chủ và form yêu cầu đặt phòng - Dương
def index(request):
    listRoomKind = RoomKind.objects.all()
    listPicture = RoomPicture.objects.all()

    return render(request, 'polls/index.html', {'listRoomKind': listRoomKind, 'listPicture': listPicture})


def reservation1(request):
    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html', {'listRoomKind': listRoomKind})


def reservation2(request, pk):
    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html', {'listRoomKind': listRoomKind, "idKind": pk})


def reservationadd(request):
    # Thêm thông tin khách hàng
    name = request.POST['name']
    gender = request.POST['gender']
    identitycard = request.POST['identitycard']
    email = request.POST['email']
    phone = request.POST['phone']
    cus = CustomerInfor(nameCustomer=name, gender=gender, identityCard=identitycard, phoneNumber=phone, email=email)
    cus.save()
    idCus = cus.idCustomer

    # Thêm vào bảng yêu cầu khách hàng
    kindroom = request.POST['kindroom']
    kind = RoomKind.objects.get(idKind=kindroom)
    customer = CustomerInfor.objects.get(idCustomer=idCus)
    checkInt = request.POST['cin']
    checkOut = request.POST['cout']
    numberRoom = int(request.POST['numberRoom'])
    numberChildren = int(request.POST['numberChildren'])
    numberAdults = int(request.POST['numberAdults'])
    note = request.POST['note']
    rq = CustomerRequest(kind=kind, customer=customer, dateCheckin=checkInt, dateCheckout=checkOut,
                         numberOfRoom=numberRoom, numberOfChildren=numberChildren, numberOfAdults=numberAdults,
                         note=note)
    rq.save()

    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html',
                  {'success': 'Request sent to the hotel!', 'listRoomKind': listRoomKind})


###

### Trang chủ admin -
def home(request):
    return render(request, 'polls/admin/home.html')


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse("polls:home"))
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="polls/admin/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    return render(request, 'polls/admin/login.html', messages.error(request, "You have successfully logged out."))


def profile(request):
    return render(request, 'polls/admin/profile.html')


# đổi mật khẩu
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('polls:change_password')
        else:
            messages.error(request, 'Please re-enter your password.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'polls/admin/change_password.html', {
        'form': form
    })


###

### Quản lý phòng và tầng - Huyền
def floor(request):
    polls_floor_list = Floor.objects.filter().order_by('idFloor')
    context = {'Floor': polls_floor_list}
    return render(request, 'polls/admin/floor.html', context)


def addfloor(request):
    return render(request, 'polls/admin/floor_add.html')


def afloor(request):
    if request.method == 'POST':
        name_floor = request.POST['name']

        fl = Floor(nameFloor=name_floor)
        fl.save()

        return floor(request)
    else:
        return render(request, 'polls/admin/error.html')


def delete_floor(request, pk):
    item = Floor.objects.get(idFloor=pk)

    item.delete()
    return floor(request)


def updateFloor(request, pk):
    floor = Floor.objects.get(idFloor=pk)
    form = FloorForm(instance=floor)
    if request.method == 'POST':
        form = FloorForm(request.POST, instance=floor)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/floor/')

    context = {'form': form}
    return render(request, 'polls/admin/floor_update.html', context)


# quản lý phòng
def room(request):
    list_floor = Floor.objects.filter()
    polls_room = Room.objects.filter().order_by('idRoom')
    return render(request, 'polls/admin/room.html', {'Room': polls_room})


def delete_room(request, pk):
    item = Room.objects.get(idRoom=pk)

    item.delete()

    return room(request)


def addroom(request):
    list_floor = Floor.objects.filter()
    list_roomkind = RoomKind.objects.filter()
    return render(request, 'polls/admin/room_add.html', {'floor': list_floor, 'roomkind': list_roomkind})


def aroom(request):
    if request.method == 'POST':
        name_room = request.POST['name_room']
        id_floor = request.POST['tang']
        id_roomkind = request.POST['loaiphong']
        trangthai = request.POST['trangthai']

        itemfloor = Floor.objects.get(idFloor=id_floor)
        itemRoomkind = RoomKind.objects.get(idKind=id_roomkind)

        addroom = Room(floor=itemfloor, kind=itemRoomkind, nameRoom=name_room, status=trangthai)
        addroom.save()
        return room(request)
    else:
        return render(request, 'polls/admin/error.html')


def updateRoom(request, pk):
    room = Room.objects.get(idRoom=pk)
    form = RoomForm(instance=room)
    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/room/')

    context = {'form': form}
    return render(request, 'polls/admin/room_update.html', context)


###

### Quản lý loại phòng - Ngân
def roomkind(request):
    roomkinds = RoomKind.objects.all()
    return render(request, 'polls/admin/roomkind.html', {'roomkinds': roomkinds})


def addroomkind(request):
    form = RoomKindForm()
    if request.method == 'POST':
        form = RoomKindForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/roomkind/')

    context = {'form': form}
    return render(request, 'polls/admin/addroomkind.html', context)


def updateRoomkind(request, pk):
    roomkind = RoomKind.objects.get(idKind=pk)
    form = RoomKindForm(instance=roomkind)
    if request.method == 'POST':
        form = RoomKindForm(request.POST, instance=roomkind)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/roomkind/')

    context = {'form': form}
    return render(request, 'polls/admin/addroomkind.html', context)


def deleteRoomKind(request, pk):
    roomkind = RoomKind.objects.get(idKind=pk)
    roomkind.delete()

    return redirect('/hihotel/admin/roomkind/')


###

### Quản lý yêu cầu đặt phòng và lập đơn đặt phòng - Thư
def bookroom(request):
    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status
    }

    return render(request, 'polls/admin/bookroom.html', res)


def editRequest(request, idRequest, status):
    record = CustomerRequest.objects.get(idRequest=idRequest)
    record.status = status
    record.save(update_fields=['status'])

    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status,
        "message": "Update success!"
    }

    return render(request, 'polls/admin/bookroom.html', res)


def deleteRequest(request, idRequest):
    CustomerRequest.objects.filter(idRequest=idRequest).delete()

    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status,
        "message": "Delete success!"
    }

    return render(request, 'polls/admin/bookroom.html', res)


def filterRoom(request, idRequest):
    dateCheckin = CustomerRequest.objects.filter(idRequest=idRequest)[0].dateCheckin
    dateCheckout = CustomerRequest.objects.filter(idRequest=idRequest)[0].dateCheckout
    kind = CustomerRequest.objects.filter(idRequest=idRequest)[0].kind
    numberOfRoom = CustomerRequest.objects.filter(idRequest=idRequest)[0].numberOfRoom

    listRoomOfKind = Room.objects.filter(kind=kind, status='OK')
    listRoom = Booking.objects.select_related('customerRequest')
    listExcept = []
    listReturn = []

    for i in listRoom:
        if i.status != 'DH':
            if kind.idKind == i.customerRequest.kind.idKind:
                if i.customerRequest.status != 'KHL':

polls/templates/polls/reservation.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HI HOTEL</title>
    <!-- Bootstrap Styles-->
    <link href="{% static 'polls/admin/assets/css/bootstrap.css' %}" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="{% static 'polls/admin/assets/css/custom-styles.css' %}" rel="stylesheet" />

	<!-- //for-mobile-apps -->
	<link href="{% static 'polls/css/font-awesome.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'polls/css/jquery-ui.css' %}" />
	<link href="{% static 'polls/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />

    <!--fonts-->
	<link href="//fonts.googleapis.com/css?family=Oswald:300,400,700" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Federo" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
	<!--//fonts-->
</head>

<body>
    <div class="banner-top">
		<div class="social-bnr-agileits">
			<ul class="social-icons3">
				<li><a href="https://www.facebook.com/" class="fa fa-facebook icon-border facebook"> </a></li>
				<li><a href="https://twitter.com/" class="fa fa-twitter icon-border twitter"> </a></li>
				<li><a href="https://plus.google.com/u/0/" class="fa fa-google-plus icon-border googleplus"> </a></li>
			</ul>
		</div>
		<div class="contact-bnr-w3-agile">
			<ul>
				<li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@hhi.com">INFO@HI.COM</a></li>
				<li><i class="fa fa-phone" aria-hidden="true"></i>090 5987 987</li>
				<li class="s-bar">
					<div class="search">
						<input class="search_box" type="checkbox" id="search_box">
						<label class="icon-search" for="search_box"><span class="glyphicon glyphicon-search"
								aria-hidden="true"></span></label>
						<div class="search_form">
							<form action="#" method="post">
								<input type="search" name="Search" placeholder=" " required=" " />
								<input type="submit" value="Search">
							</form>
						</div>
					</div>
				</li>
			</ul>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="w3_navigation">
		<div class="container">
			<nav class="navbar navbar-default">
				<div style="background-color: transparent" class="navbar-header navbar-left">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
						data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<h1><a class="navbar-brand" href="{% url 'polls:index'%}"
							style="text-align: center;"><span>HI</span>
						</a></h1>
				</div>
			</nav>
		</div>
	</div>
    <div id="wrap">

        {% if success %}
            <p style="color: red; font-size: 25px; text-align: center;">{{success}}</p>
        {% endif %}

        <div id="page-wrap">
            <div id="page-inn">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            RESERVATION <small></small>
                        </h1>
                    </div>
                </div>


                <div class="row">

                    <div class="col-md-5 col-sm-5">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                PERSONAL INFORMATION
                            </div>
                            <div class="panel-body">
                                {% csrf_token %}
                                <form name="form" action="{% url 'polls:reservationadd'%}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input name="name" class="form-control" required>

                                    </div>

                                    <div class="form-group">
                                        <label>Gender</label>
                                        <select name="gender" class="form-control" required>
                                            <option value="Na">Nam (Male)</option>
                                            <option value="Nu">Nữ (Female)</option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Identity Card </label>
                                        <input name="identitycard" type="text" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label>Email</label>
                                        <input name="email" type="email" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label>Phone</label>
                                        <input name="phone" type="text" class="form-control" required>
                                    </div>
                            </div>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    RESERVATION INFORMATION
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label>Kind Room</label>
                                        <select name="kindroom" class="form-control" required>
                                            {% if not idKind %}
                                                <option value="">Choose</option>
                                            {% endif %}
                                            {% if listRoomKind %}
                                                {% for itemKind in listRoomKind %}
                                                    {% if idKind and itemKind.idKind == idKind %}
                                                        <option selected value="{{itemKind.idKind}}">{{ itemKind.get_nameKind_display }}</option>
                                                    {% else %}
                                                        <option value="{{itemKind.idKind}}">{{ itemKind.get_nameKind_display }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endif %}
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Check-In</label>
                                        <input name="cin" type="datetime-local" class="form-control">
                                    </div>

                                    <div class="form-group">
                                        <label>Check-Out</label>
                                        <input name="cout" type="datetime-local" class="form-control">
                                    </div>

                                    <div class="form-group">
                                        <label>Number Room</label>
                                        <input name="numberRoom" type="text" class="form-control">
                                    </div>

                                    <div class="form-group">
                                        <label>Number Of Children</label>
                                        <input name="numberChildren" type="text" class="form-control">
                                    </div>

                                    <div class="form-group">
                                        <label>Number Of Adults</label>
                                        <input name="numberAdults" type="text" class="form-control">
                                    </div>

                                    <div class="form-group">
                                        <label>Note</label><br />
                                        <textarea style="width: 100%" name="note" cols="89" rows="4"></textarea>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>

                    <div class="button">
                        <button class="btnDT"> <a href="{% url 'polls:index'%}">Back</a></button>
                        <input type="submit" value="Send" name="submit" class="btnDT" style="background-color: #ffce14; padding: 0.4em 2em; color: #000000; display: inline-block; border: 2px solid #ecbf11;"/>
                    </div>
                </form>
                </div>

            </div>
            <!-- /. PAGE INNER  -->
        </div>

        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
    <script src="{% static 'polls/admin/assets/js/jquery-1.10.2.js' %}"></script>
    <!-- Bootstrap Js -->
    <script src="{% static 'polls/admin/assets/js/bootstrap.min.js' %}"></script>
    <!-- Metis Menu Js -->
    <script src="{% static 'polls/admin/assets/js/bootstrap.min.js' %}x"></script>



</body>

</html>