djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('hihotel/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('reservation/<int:pk>/', views.reservation2, name='reservation.html'),
    path('reservation/', views.reservation1, name='reservation.html'),
    path('reservation/add', views.reservationadd, name='reservationadd'),
    path('admin/home', views.home, name='home'),
    path('admin/', views.login, name='login'),
    path("admin/logout/", views.logout_request, name="logout"),
    path("admin/profile/", views.profile, name="profile"),
    path("admin/change_password/", views.change_password, name='change_password'),
    path('admin/floor/', views.floor, name='floor'),
    path('admin/floor/add', views.addfloor, name='addfloor'),
    path('admin/floor/afloor', views.afloor, name='afloor'),
    #     path('admin/floor/update/<int:pk>', views.update_floor, name='update_floor'),
    path('admin/update_floor/<str:pk>/', views.updateFloor, name='update_floor'),
    path('admin/floor/del/<int:pk>', views.delete_floor, name='delete_floor'),
    path('admin/room/', views.room, name='room'),
    path('admin/room/add', views.addroom, name='addroom'),
    path('admin/room/aroom', views.aroom, name='aroom'),
    #     path('admin/room/upfloor/<int:pk>', views.uproom, name='uproom'),
    path('admin/update_room/<str:pk>/', views.updateRoom, name='update_room'),
    path('admin/room/del/<int:pk>', views.delete_room, name='delete_room'),
    path('admin/roomkind/', views.roomkind, name='roomkind'),
    path('admin/addroomkind', views.addroomkind, name='addroomkind'),
    path('admin/update_roomkind/<str:pk>/', views.updateRoomkind, name='update_roomkind'),
    path('admin/delete_roomkind/<str:pk>/', views.deleteRoomKind, name='delete_roomkind'),
    path('admin/bookroom/', views.bookroom, name='bookroom'),
    path('admin/bookroom/edit/<int:idRequest>/<str:status>/', views.editRequest, name='editRequest'),
    path('admin/bookroom/delete/<str:idRequest>/', views.deleteRequest, name="deleteRequest"),
    path('admin/bookroom/filter/<str:idRequest>/', views.filterRoom, name="filterRoom"),
    path('admin/bookroom/bookfilter/', views.booking, name="booking"),
    path('admin/booking/', views.bookingManage, name="bookingManage"),
    path('admin/booking/edit/<int:id>/<str:status>/', views.bookingEdit, name="bookingEdit"),
    path('admin/booking/delete/<int:id>/', views.bookingDelete, name="bookingDelete"),
]

polls/models.py
from django.db import models


class Floor(models.Model):
    idFloor = models.BigAutoField(primary_key=True)
    nameFloor = models.CharField(max_length=100)

    class Meta:
        db_table = 'Floor'


class RoomKind(models.Model):
    KIND = [
        ('STD-S', 'Standard - Singer bed'),
        ('STD-D', 'Standard - Double bed'),
        ('SUP-S', 'Superior - Single bed'),
        ('SUP-D', 'Superior - Double bed'),
    ]
    idKind = models.BigAutoField(primary_key=True)
    nameKind = models.CharField(max_length=100, choices=KIND)
    price = models.CharField(max_length=100)
    descript = models.TextField()

    class Meta:
        db_table = 'RoomKind'


class RoomPicture(models.Model):
    idPicture = models.BigAutoField(primary_key=True)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    linkPicture = models.CharField(max_length=100)

    class Meta:
        db_table = 'RoomPicture'


class Room(models.Model):
    STATUS = [
        ('OK', 'Phòng sẵn sàng'),
        ('ER', 'Phòng hỏng')
    ]
    idRoom = models.BigAutoField(primary_key=True)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    nameRoom = models.CharField(max_length=100)
    status = models.CharField(max_length=100, choices=STATUS, default='OK')

    class Meta:
        db_table = 'Room'


class CustomerInfor(models.Model):
    GENDER = [
        ('Na', 'Nam'),
        ('Nu', 'Nữ'),
        ('Kh', 'Khác')
    ]
    idCustomer = models.BigAutoField(primary_key=True)
    nameCustomer = models.CharField(max_length=50)
    gender = models.CharField(max_length=100, choices=GENDER)
    identityCard = models.CharField(max_length=12)
    phoneNumber = models.CharField(max_length=12)
    email = models.CharField(max_length=30)

    class Meta:
        db_table = 'CustomerInfo'


class CustomerRequest(models.Model):
    STATUS = [
        ('CD', 'Chờ duyệt'),
        ('HL', 'Hợp lệ'),
        ('KHL', 'Không hợp lệ')
    ]
    idRequest = models.BigAutoField(primary_key=True)
    customer = models.ForeignKey(CustomerInfor, on_delete=models.CASCADE)
    kind = models.ForeignKey(RoomKind, on_delete=models.CASCADE)
    dateCheckin = models.DateTimeField()
    dateCheckout = models.DateTimeField()
    numberOfRoom = models.IntegerField()
    numberOfChildren = models.IntegerField()
    numberOfAdults = models.IntegerField()
    status = models.CharField(max_length=100, choices=STATUS, default='CD')
    note = models.TextField(default="")

    class Meta:
        db_table = 'CustomerRequest'

class Booking(models.Model):
    STATUS = [
        ('DN', 'Đã nhận phòng'),
        ('DH', 'Đã hủy'),
        ('CN', 'Chờ nhận phòng')
    ]
    idBooking = models.BigAutoField(primary_key=True)
    customerRequest = models.ForeignKey(CustomerRequest, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    status = models.CharField(max_length=100, choices=STATUS, default='CN')
    note = models.CharField(max_length=100)

    class Meta:
        db_table = 'Booking'

polls/forms.py
from django import forms
from .models import *


class RoomKindForm(forms.ModelForm):
    class Meta:
        model = RoomKind
        fields = ('idKind', 'nameKind', 'price', 'descript')


class FloorForm(forms.ModelForm):
    class Meta:
        model = Floor
        fields = ('idFloor', 'nameFloor')


class RoomForm(forms.ModelForm):
    # floor = forms.ModelChoiceField(queryset=Floor.objects.all(),
    #                                 empty_label="............")
    # kind = forms.ModelChoiceField(queryset=RoomKind.objects.all(),
    #                                 empty_label="............")
    class Meta:
        model = Room
        fields = ('idRoom', 'floor', 'kind', 'nameRoom', 'status')

polls/views.py
from email.policy import HTTP
from django.http import HttpResponse
from .models import *
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
# from HotelManage.polls.models import RoomKind
from .forms import *
from .models import *


### Trang chủ và form yêu cầu đặt phòng - Dương
def index(request):
    listRoomKind = RoomKind.objects.all()
    listPicture = RoomPicture.objects.all()

    return render(request, 'polls/index.html', {'listRoomKind': listRoomKind, 'listPicture': listPicture})


def reservation1(request):
    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html', {'listRoomKind': listRoomKind})


def reservation2(request, pk):
    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html', {'listRoomKind': listRoomKind, "idKind": pk})


def reservationadd(request):
    # Thêm thông tin khách hàng
    name = request.POST['name']
    gender = request.POST['gender']
    identitycard = request.POST['identitycard']
    email = request.POST['email']
    phone = request.POST['phone']
    cus = CustomerInfor(nameCustomer=name, gender=gender, identityCard=identitycard, phoneNumber=phone, email=email)
    cus.save()
    idCus = cus.idCustomer

    # Thêm vào bảng yêu cầu khách hàng
    kindroom = request.POST['kindroom']
    kind = RoomKind.objects.get(idKind=kindroom)
    customer = CustomerInfor.objects.get(idCustomer=idCus)
    checkInt = request.POST['cin']
    checkOut = request.POST['cout']
    numberRoom = int(request.POST['numberRoom'])
    numberChildren = int(request.POST['numberChildren'])
    numberAdults = int(request.POST['numberAdults'])
    note = request.POST['note']
    rq = CustomerRequest(kind=kind, customer=customer, dateCheckin=checkInt, dateCheckout=checkOut,
                         numberOfRoom=numberRoom, numberOfChildren=numberChildren, numberOfAdults=numberAdults,
                         note=note)
    rq.save()

    listRoomKind = RoomKind.objects.all()

    return render(request, 'polls/reservation.html',
                  {'success': 'Request sent to the hotel!', 'listRoomKind': listRoomKind})


###

### Trang chủ admin -
def home(request):
    return render(request, 'polls/admin/home.html')


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse("polls:home"))
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="polls/admin/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    return render(request, 'polls/admin/login.html', messages.error(request, "You have successfully logged out."))


def profile(request):
    return render(request, 'polls/admin/profile.html')


# đổi mật khẩu
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('polls:change_password')
        else:
            messages.error(request, 'Please re-enter your password.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'polls/admin/change_password.html', {
        'form': form
    })


###

### Quản lý phòng và tầng - Huyền
def floor(request):
    polls_floor_list = Floor.objects.filter().order_by('idFloor')
    context = {'Floor': polls_floor_list}
    return render(request, 'polls/admin/floor.html', context)


def addfloor(request):
    return render(request, 'polls/admin/floor_add.html')


def afloor(request):
    if request.method == 'POST':
        name_floor = request.POST['name']

        fl = Floor(nameFloor=name_floor)
        fl.save()

        return floor(request)
    else:
        return render(request, 'polls/admin/error.html')


def delete_floor(request, pk):
    item = Floor.objects.get(idFloor=pk)

    item.delete()
    return floor(request)


def updateFloor(request, pk):
    floor = Floor.objects.get(idFloor=pk)
    form = FloorForm(instance=floor)
    if request.method == 'POST':
        form = FloorForm(request.POST, instance=floor)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/floor/')

    context = {'form': form}
    return render(request, 'polls/admin/floor_update.html', context)


# quản lý phòng
def room(request):
    list_floor = Floor.objects.filter()
    polls_room = Room.objects.filter().order_by('idRoom')
    return render(request, 'polls/admin/room.html', {'Room': polls_room})


def delete_room(request, pk):
    item = Room.objects.get(idRoom=pk)

    item.delete()

    return room(request)


def addroom(request):
    list_floor = Floor.objects.filter()
    list_roomkind = RoomKind.objects.filter()
    return render(request, 'polls/admin/room_add.html', {'floor': list_floor, 'roomkind': list_roomkind})


def aroom(request):
    if request.method == 'POST':
        name_room = request.POST['name_room']
        id_floor = request.POST['tang']
        id_roomkind = request.POST['loaiphong']
        trangthai = request.POST['trangthai']

        itemfloor = Floor.objects.get(idFloor=id_floor)
        itemRoomkind = RoomKind.objects.get(idKind=id_roomkind)

        addroom = Room(floor=itemfloor, kind=itemRoomkind, nameRoom=name_room, status=trangthai)
        addroom.save()
        return room(request)
    else:
        return render(request, 'polls/admin/error.html')


def updateRoom(request, pk):
    room = Room.objects.get(idRoom=pk)
    form = RoomForm(instance=room)
    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/room/')

    context = {'form': form}
    return render(request, 'polls/admin/room_update.html', context)


###

### Quản lý loại phòng - Ngân
def roomkind(request):
    roomkinds = RoomKind.objects.all()
    return render(request, 'polls/admin/roomkind.html', {'roomkinds': roomkinds})


def addroomkind(request):
    form = RoomKindForm()
    if request.method == 'POST':
        form = RoomKindForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/roomkind/')

    context = {'form': form}
    return render(request, 'polls/admin/addroomkind.html', context)


def updateRoomkind(request, pk):
    roomkind = RoomKind.objects.get(idKind=pk)
    form = RoomKindForm(instance=roomkind)
    if request.method == 'POST':
        form = RoomKindForm(request.POST, instance=roomkind)
        if form.is_valid():
            form.save()
            return redirect('/hihotel/admin/roomkind/')

    context = {'form': form}
    return render(request, 'polls/admin/addroomkind.html', context)


def deleteRoomKind(request, pk):
    roomkind = RoomKind.objects.get(idKind=pk)
    roomkind.delete()

    return redirect('/hihotel/admin/roomkind/')


###

### Quản lý yêu cầu đặt phòng và lập đơn đặt phòng - Thư
def bookroom(request):
    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status
    }

    return render(request, 'polls/admin/bookroom.html', res)


def editRequest(request, idRequest, status):
    record = CustomerRequest.objects.get(idRequest=idRequest)
    record.status = status
    record.save(update_fields=['status'])

    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status,
        "message": "Update success!"
    }

    return render(request, 'polls/admin/bookroom.html', res)


def deleteRequest(request, idRequest):
    CustomerRequest.objects.filter(idRequest=idRequest).delete()

    list_request = CustomerRequest.objects.order_by('status')
    list_status = CustomerRequest.status.field.choices

    res = {
        "list_request": list_request,
        "list_status": list_status,
        "message": "Delete success!"
    }

    return render(request, 'polls/admin/bookroom.html', res)


def filterRoom(request, idRequest):
    dateCheckin = CustomerRequest.objects.filter(idRequest=idRequest)[0].dateCheckin
    dateCheckout = CustomerRequest.objects.filter(idRequest=idRequest)[0].dateCheckout
    kind = CustomerRequest.objects.filter(idRequest=idRequest)[0].kind
    numberOfRoom = CustomerRequest.objects.filter(idRequest=idRequest)[0].numberOfRoom

    listRoomOfKind = Room.objects.filter(kind=kind, status='OK')
    listRoom = Booking.objects.select_related('customerRequest')
    listExcept = []
    listReturn = []

    for i in listRoom:
        if i.status != 'DH':
            if kind.idKind == i.customerRequest.kind.idKind:
                if i.customerRequest.status != 'KHL':

polls/templates/polls/admin/error.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Administrator	</title>
    <!-- Bootstrap Styles-->
    <link href="{% static 'polls/admin/assets/css/bootstrap.css' %}" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="{% static 'polls/admin/assets/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="{% static 'polls/admin/assets/js/morris/morris-0.4.3.min.css' %}" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="{% static 'polls/admin/assets/css/custom-styles.css' %} " rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="home.php">  </a>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="usersetting.php"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="settings.php"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="logout.php"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                        <a class="active-menu" href="{% url 'polls:admin'%}"><i class="fa fa-dashboard"></i> Trang chủ</a>
                    </li>
                    <li>
                        <a href="{% url 'polls:floor'%}"><i class="fa fa-desktop"></i> Floor</a>
                    </li>
                    <li>
                        <a href="{% url 'polls:room'%}"><i class="fa fa-desktop"></i> Room</a>
                    </li>
					<li>
                        <a href="{% url 'polls:roomkind'%}"><i class="fa fa-bar-chart-o"></i> Roomkind</a>
                    </li>
                    <li>
                        <a href="{% url 'polls:bookroom'%}"><i class="fa fa-bar-chart-o"></i> RoomBook</a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>




					</ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">


                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                           Có lỗi xảy ra
                        </h1>
                    </div>
                </div>


            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
    <script src="{% static 'polls/admin/assets/js/jquery-1.10.2.js' %}"></script>
    <!-- Bootstrap Js -->
    <script src="{% static 'polls/admin/assets/js/bootstrap.min.js' %}"></script>
    <!-- Metis Menu Js -->
    <script src="{% static 'polls/admin/assets/js/jquery.metisMenu.js' %}"></script>
    <!-- Morris Chart Js -->
    <script src="{% static 'polls/admin/assets/js/morris/raphael-2.1.0.min.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'polls/admin/assets/js/custom-scripts.js' %}"></script>


</body>

</html>

polls/templates/polls/admin/floor.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Administrator	</title>

    {% include './include/link_lib.html' %}
</head>

<body>
    <div id="wrapper">
        {% include "./include/nav_horizontal.html" %}
        {% include "./include/nav_vertical.html" %}

        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Floor <small>List </small>
                        </h1>
                    </div>
                </div>
                <!-- /. ROW  -->

                <div>
                    <a  href="{% url 'polls:addfloor'%}">
                        <button style="float: right; margin: 20px;" class="btn btn-primary" type="button">
                            Add floor  <span class="badge"></span>
                        </button>
                    </a>
                </div>
				<div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <table id="table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th width="20%">ID</th>
                                            <th width="50%">Name</th>
											<th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for floor in Floor %}
                                            <tr>
                                                <th>{{ floor.idFloor}}</th>
                                                <th>{{floor.nameFloor}}</th>
                                                <th>

                                                    <a href="{% url 'polls:update_floor' floor.idFloor %}" class='btn btn-primary'>Edit</a>
                                                    <a onclick="return confirm('Are you sure?')" href="{% url 'polls:delete_floor' floor.idFloor %}" class='btn btn-primary'>Delete</a>
                                                </th>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- End  Basic Table  -->
                </div>
                <!-- /. ROW  -->

            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->

    <!-- JS Scripts-->
    <!-- Metis Menu Js -->
    <script src="{% static 'polls/admin/assets/js/jquery.metisMenu.js' %}"></script>
    <!-- Morris Chart Js -->
    <script src="{% static 'polls/admin/assets/js/morris/raphael-2.1.0.min.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'polls/admin/assets/js/custom-scripts.js' %}"></script>

</body>

</html>

polls/templates/polls/admin/login.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hi Admin</title>

    {% include './include/link_lib.html' %}
</head>

<body>
    <div id="clouds">
        <div class="cloud x1"></div>
        <div class="cloud x2"></div>
        <div class="cloud x3"></div>
        <div class="cloud x4"></div>
        <div class="cloud x5"></div>
    </div>
    {% block content %}
    <div class="container">
        <div id="login">
           <form action="{% url 'polls:login' %}" method="post">
                <fieldset class="clearfix">
                    {% csrf_token%}
                    <div class="">
                        {% for message in messages %}
                            <p {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} ><b>{{message}}</b></p>
                        {% endfor %}
                    </div>
                    <p><span class="fontawesome-user"></span><input type="text" name="username" class="form_login" placeholder="username"></p>
                    <p><span class="fontawesome-lock"></span><input type="password" name="password" class="form_login" placeholder="password"></p>
                    <p><input type="submit" name="sub" value="Login"></p>
                </fieldset>
            </form>

        </div>
    </div>
    {% endblock %}
    <div class="bottom">
        <h3><a href="{% url 'polls:index'%}">HI HOMEPAGE</a></h3>
    </div>
</body>
</html>

polls/templates/polls/admin/room.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Administrator	</title>

    {% include './include/link_lib.html' %}
</head>

<body>
    <div id="wrapper">
        {% include "./include/nav_horizontal.html" %}
        {% include "./include/nav_vertical.html" %}

        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Room <small>List </small>
                        </h1>
                    </div>
                </div>
                <!-- /. ROW  -->

                <div>
                    <a  href="{% url 'polls:addroom'%}">
                        <button style="float: right; margin: 20px;" class="btn btn-primary" type="button">
                            Add room  <span class="badge"></span>
                        </button>
                    </a>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <table id="table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
				            <th>Name Room</th>
                                            <th>Room Kind</th>
                                            <th>Floor</th>
		                            <th>Status</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       {% for room in Room %}
                                            <tr>
                                                <th>{{room.idRoom}}</th>
						<th>{{room.nameRoom}}</th>
                                                <th>{{room.kind.get_nameKind_display}}</th>
                                                <th>{{room.floor.nameFloor }}</th>
                                                <th>{{room.status }}</th>
                                                <th>
                                                    <a href="{% url 'polls:update_room' room.idRoom %}"  class='btn btn-primary'>Edit</a>
                                                    <a onclick="return confirm('Are you sure?')"  href="{% url 'polls:delete_room' room.idRoom %}" class='btn btn-primary'>Delete</a>
                                                </th>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                      <!-- End  Basic Table  -->
                </div>
                <!-- /. ROW  -->
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->

    <!-- JS Scripts-->
    <!-- Metis Menu Js -->
    <script src="{% static 'polls/admin/assets/js/jquery.metisMenu.js' %}"></script>
    <!-- Morris Chart Js -->
    <script src="{% static 'polls/admin/assets/js/morris/raphael-2.1.0.min.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'polls/admin/assets/js/custom-scripts.js' %}"></script>

</body>

</html>